-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'UPLOAD', 'DOWNLOAD', 'DELETE', 'RESTORE', 'RENAME', 'MOVE', 'CREATE_FOLDER', 'SHARE_CREATE', 'SHARE_REVOKE', 'PERMISSION_GRANT', 'PERMISSION_REVOKE', 'USER_CREATE', 'USER_UPDATE', 'USER_DEACTIVATE', 'DEPARTMENT_CREATE', 'DEPARTMENT_UPDATE', 'STAR', 'UNSTAR', 'PURGE', 'TWO_FACTOR_ENABLE', 'TWO_FACTOR_DISABLE', 'PASSWORD_CHANGE', 'SESSION_REVOKE', 'SETTINGS_UPDATE', 'AUTO_CLEANUP', 'ORDER_CREATE', 'ORDER_STATUS_UPDATE', 'PAYMENT_RECORD', 'PAYMENT_DELETE', 'CUSTOMER_AUTO_UPDATE') NOT NULL;

-- AlterTable
ALTER TABLE `customers` ADD COLUMN `address` TEXT NULL,
    ADD COLUMN `email` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL,
    ADD COLUMN `taxNumber` VARCHAR(191) NULL,
    ADD COLUMN `taxOffice` VARCHAR(191) NULL;
