-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('SHARE_GRANTED', 'QUOTA_WARNING', 'ORDER_CREATED', 'ORDER_STATUS_CHANGED', 'PAYMENT_RECORDED', 'ORDER_OVERDUE', 'CHAT_DM', 'CHAT_MENTION', 'APPROVAL_REQUESTED', 'APPROVAL_DECIDED', 'UPLOAD_RECEIVED', 'LINK_EXPIRING') NOT NULL;

-- AlterTable
ALTER TABLE `share_links` ADD COLUMN `expiryNotifiedAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `upload_requests` ADD COLUMN `expiryNotifiedAt` DATETIME(3) NULL;
